### ISSUE TITLE
PytestUnhandledThreadExceptionWarning being emitted when running tests

### ISSUE THREAD

**Issue by kbakk** [JonatanMartens/pyzeebe#116]
**Describe the bug**
When running `pytest` (with no `filterwarnings`) on `development` branch, a list of warnings of type `PytestUnhandledThreadExceptionWarning` are shown. 

The warnings where introduced in pytest 6.2, however the exceptions have alwawys been there. 

<details>
<summary>pytest output</summary>

```sh
❯ pipenv run pytest
============================================== test session starts ==============================================
platform darwin -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kristofferb/Code/fork/pyzeebe, configfile: pytest.ini
plugins: grpc-0.8.0, mock-3.5.1
collected 144 items                                                                                             

tests/integration/integration_test.py ....                                                                [  2%]
tests/unit/client/client_test.py .......                                                                  [  7%]
tests/unit/credentials/camunda_cloud_credentials_test.py ..                                               [  9%]
tests/unit/credentials/oauth_credentials_test.py ..                                                       [ 10%]
tests/unit/decorators/zeebe_decorator_base_test.py ....                                                   [ 13%]
tests/unit/grpc_internals/zeebe_adapter_base_test.py ......................                               [ 28%]
tests/unit/grpc_internals/zeebe_job_adapter_test.py ..................                                    [ 40%]
tests/unit/grpc_internals/zeebe_message_adapter_test.py ......                                            [ 45%]
tests/unit/grpc_internals/zeebe_workflow_adapter_test.py ..............                                   [ 54%]
tests/unit/job/job_test.py ......                                                                         [ 59%]
tests/unit/task/task_test.py ....                                                                         [ 61%]
tests/unit/worker/task_handler_test.py .......................                                            [ 77%]
tests/unit/worker/task_router_test.py .........                                                           [ 84%]
tests/unit/worker/worker_test.py .......................                                                  [100%]

=============================================== warnings summary ================================================
tests/unit/client/client_test.py::test_publish_message
  /Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-11
  
  Traceback (most recent call last):
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 508, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/unit/grpc_internals/zeebe_adapter_base_test.py::test_close_after_retried_internal
  /Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-29
  
  Traceback (most recent call last):
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 508, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/unit/grpc_internals/zeebe_job_adapter_test.py::test_throw_error_common_errors_called
  /Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-95
  
  Traceback (most recent call last):
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 508, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/unit/grpc_internals/zeebe_message_adapter_test.py::test_publish_message_common_errors_called
  /Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-151
  
  Traceback (most recent call last):
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 508, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/unit/grpc_internals/zeebe_workflow_adapter_test.py::test_create_workflow_errors_common_errors_called
  /Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-167
  
  Traceback (most recent call last):
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/Users/kristofferb/.local/share/virtualenvs/pyzeebe-FU8Qn1Ev/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 508, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================= 144 passed, 5 warnings in 13.58s ========================================
```

</details>

**To Reproduce**

With Python 3.8, run `pipenv run pytest`

**Expected behavior**

No warnings shown

---

I created PR #115 to suppress these warnings, however this doesn't solve the root cause.

**Comment by JonatanMartens** [comment]
Closing, as the warnings do not appear anymore after #117
